# CLI.
gfcli:
  gen:
    dao:
      - link:            "mysql:root:@tcp(127.0.0.1:3306)/gfast-v32"
        tables:          "sys_camera"
        removePrefix:    "gf_"
        descriptionTag:  true
        noModelComment:  true
        path: "./internal/app/system"